### PR TITLE
Fix compatibility with the sudoers file

### PR DESCRIPTION
**Pull request by qsantos**
Starting sshuttle without having to type in one's password requires to
put the sudo-ed command in the `/etc/sudoers` file. However, sshuttle
sets an environment variable, which cannot be done as-is in the sudoers
file. This fix prepends the `/usr/bin/env` command, which allows one to
pass fixed environment variables to a sudo-ed command.

In practice, the sub-command:

```
sudo PYTHONPATH=/usr/lib/python3/dist-packages -- \
        /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall
```

becomes

```
sudo /usr/bin/env PYTHONPATH=/usr/lib/python3/dist-packages \
        /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall
```

### CODE REVIEW

**Comment by sublimino** [comment]
@qsantos smart fix, thanks! Can confirm this works for me with a visudo entry of 

```/usr/bin/env PYTHONPATH=/usr/lib/python3/dist-packages /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall``` 

Any chance of getting it merged @apenwarr?

**Comment by vallovic** [comment]
Thanks, mate, been searching a lot for this and finally I could make it work! 😄 

However, I have to note that in your fix there's a comma missing right after _'/usr/bin/env'_, without that the program will crash.

**Comment by vallovic** [comment]
So, if anyone is searching for a solution to run sshuttle without having to put the root password everytime, follow these steps:

1. Create a sudoers file using visudo `sudo visudo -f /etc/sudoers.d/sshuttle`

2. Paste the following
```
Cmnd_Alias SSHUTTLE = /usr/bin/env PYTHONPATH=/usr/lib/python3.5/dist-packages /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall
Cmnd_Alias SSHUTTLEDAEMON = /usr/bin/env PYTHONPATH=/usr/lib/python3.5/dist-packages /usr/bin/python3 /usr/bin/sshuttle --method auto --firewall --syslog

username ALL=NOPASSWD: SSHUTTLE
username ALL=NOPASSWD: SSHUTTLEDAEMON
```
This allows you to run both normal and daemon versions without inserting sudo password. Please note that you have to change _username_ to yours and possibly may have to change some of the locations (p.e. /usr/bin/sshuttle to /usr/local/bin/sshuttle - which was my case)

3. Save and exit the file so the changes are submitted.

**Comment by qsantos** [comment]
Oh! Sorry for this, I should have copied the file from my installation rather than re-writing the change by hand. I fixed the commit!

**Comment by joaompssantos** [comment]
@qsantos can you please make a pull request of this change to the main sshuttle repository (https://github.com/sshuttle/sshuttle)?

**Comment by qsantos** [comment]
[Done](https://github.com/sshuttle/sshuttle/pull/204).

**Comment by joaompssantos** [comment]
Thanks! Hopefully it will be accepted as I have been searching for this solution for a long time.

**Pull request closed without merging**
